version: '3.8'

services:
  keycloak:
    ports:
      - "8090:8080"

  mongodb:
    ports:
      - "27017:27017"

  ak-products-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5077:8080"

  ak-discount-grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"

  ak-shoppingcart-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5079:8080"

  postgres:
    ports:
      - "5432:5432"

  ak-order-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5080:8080"

  ak-useridentity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5085:8080"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m

  kibana:
    ports:
      - "5601:5601"

  ak-gateway-api:
    ports:
      - "8000:8000"
